server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 1000
#    password: guguan2019
mybatis:
  type-aliases-package: com.liuyongde.demo.domain
  mapper-locations: classpath*:com/liuyongde/demo/mapper/xml/*.xml

